---
name: Build resume
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cp terraform.tfvars.example terraform.tfvars
      - run: ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: rendered-resume
          path: |
            resume.html
            resume.md
            resume.pdf
...